Det 2421 non detr voxelization
luminartech/mmdetection3d pull request #11
Opened 2022-09-09 20:51 UTC by ramchandra-karandikar

Thanks for your contribution and we appreciate it a lot. The following instructions would make your pull request more healthy and more easily get feedback. If you do not understand some items, don't worry, just make the pull request and seek help from maintainers.

## Motivation

A. Need a way to support different models in parallel. Therefore: Adding a separate configuration file to specify model path and model configuration file path. 
TRT engine generations could use this configuration file to read off relevant (& compatible) model and config file to parse.

B. Need a separate Non-deterministic version of the model 

## Modification

a. New model file and associated configuration file.
b. Configuration file specifying the current model path and the correct configuration file to be used.

## Use cases (Optional)
Need a way to support different models in parallel. 

## Checklist
1. Pre-commit or other linting tools are used to fix the potential lint issues. [NA]
2. The modification is covered by complete unit tests. If not, please add more unit test to ensure the correctness.
3. If the modification has potential influence on downstream projects, this PR should be tested with downstream projects.
4. The documentation has been modified accordingly, like docstring or example tutorials.

2022-09-09 21:17 UTC, siddharthanpr requested changes
Let's add the config file to the model. If we commit both it will get hard to maintain versions.

2022-09-09 21:31 UTC, ramchandra-karandikar commented
That will be part of a separate PR

2022-09-09 21:45 UTC, siddharthanpr commented
> That will be part of a separate PR

Let's do that PR first. We don't want to deal with config file issues again.

2022-09-09 22:02 UTC, ramchandra-karandikar commented
That will delay deployment of the model until mid-next week

2022-09-23 16:03 UTC, siddharthanpr commented
already merged in https://github.com/luminartech/mmdetection3d/pull/15

2022-09-23 16:03 UTC, closed without merging

2022-09-25 23:22 UTC, siddharthanpr commented on configs/centerpoint/centerpoint_03pillar_kitti_lum_nonDeterministic.py
> +        tasks=[
Is this the order of tasks we use still? If this is the order that is embedded in non deterministic voxelization model, wee need to change the order to ['Pedestrian', 'Cyclist', 'Car', 'Large_vehicle'] instead of the below

2022-09-26 17:05 UTC, ramchandra-karandikar commented on configs/centerpoint/centerpoint_03pillar_kitti_lum_nonDeterministic.py
> +        tasks=[
Yes, This is still the order that we use. Is it possible for you to read the order off of the configuration file?

2022-09-26 17:25 UTC, siddharthanpr commented on configs/centerpoint/centerpoint_03pillar_kitti_lum_nonDeterministic.py
> +        tasks=[
but where is the correct order. These tasks are not ordered right. Task index 2 is clearly CAR in the network.

2022-09-26 17:27 UTC, ramchandra-karandikar commented on configs/centerpoint/centerpoint_03pillar_kitti_lum_nonDeterministic.py
> +        tasks=[
The order embedded within 'class_names = ['Pedestrian', 'Cyclist', 'Car', 'Large_vehicle']'

2022-09-26 17:27 UTC, ramchandra-karandikar commented on configs/centerpoint/centerpoint_03pillar_kitti_lum_nonDeterministic.py
> +        tasks=[
Look for that variable: class_names

2022-09-26 17:31 UTC, siddharthanpr commented on configs/centerpoint/centerpoint_03pillar_kitti_lum_nonDeterministic.py
> +        tasks=[
But 1) that's not the one used by the network. 2) When we put more than one class in a task, We can't have arbitrarty order in `class_names`. Config file has class_names as an independent variable that is not used anywhere for creating the heads/labels.

2022-09-26 17:33 UTC, siddharthanpr commented on configs/centerpoint/centerpoint_03pillar_kitti_lum_nonDeterministic.py
> +        tasks=[
If you can show me code where they use the order in class names, then I'd be convinced to use the same.

2022-09-26 18:06 UTC, ramchandra-karandikar commented on configs/centerpoint/centerpoint_03pillar_kitti_lum_nonDeterministic.py
> +        tasks=[
Can you elaborate (1)? The sequence specified within this class_names variable seems to be the right sequence. 
Can you specify which other variable is being used by the network exactly, if not class_names?
(2) Can we avoid having another rule to create required sequence of class-names&tasks?

2022-09-26 18:27 UTC, siddharthanpr commented on configs/centerpoint/centerpoint_03pillar_kitti_lum_nonDeterministic.py
> +        tasks=[
class_names happens to be the right order. But the code does not use it. The network uses only the ones in tasks.

2022-09-26 18:28 UTC, ramchandra-karandikar commented on configs/centerpoint/centerpoint_03pillar_kitti_lum_nonDeterministic.py
> +        tasks=[
But, how does the code get the order that is different from the one that's listed within tasks? Is it hardcoded in the code?

2022-09-26 18:36 UTC, siddharthanpr commented on configs/centerpoint/centerpoint_03pillar_kitti_lum_nonDeterministic.py
> +        tasks=[
I want you to find that. Where it gets the order from. If you can show that it gets it from class_names, then we have no problem

2022-09-26 18:36 UTC, siddharthanpr commented on configs/centerpoint/centerpoint_03pillar_kitti_lum_nonDeterministic.py
> +        tasks=[
But AFAIK it does not get it from there