Support conversion of CenterPoint model with configurable voxelization.
luminartech/mmdetection3d pull request #28
Opened 2022-10-24 17:53 UTC by meremeev

Support conversion of CenterPoint model with configurable voxelization.
Add script to generate TRT engines for fp32/fp16

2022-10-24 18:33 UTC, siddharthanpr commented on mmdet3d/apis/convert.py
> +    if model.with_dynamic_voxelization or model.cfg['model']['type'] == 'CenterPoint_dynamicVoxel':
It is enought to only check for model.with_dynamic_voxelization. the second check is redundant.

2022-10-24 18:34 UTC, siddharthanpr commented on mmdet3d/models/detectors/centerpoint.py
> +        class SubModel_dynamicVoxel(torch.nn.Module):
I dont think we need this. All we need is an if case in forward for the original SubModel

2022-10-24 18:42 UTC, thomashuang1 approved these changes
The conversion config for FP32/FP16 is enabled.

2022-10-24 18:48 UTC, siddharthanpr commented on mmdet3d/models/detectors/centerpoint.py
> +                self.output_names = None
Can we just use an if case to choose between two forward functions? 
something like 
``` 
if self.with_dynamic_voxelization:
    self.forward = ...
else:
     self.forward = ...
```

put all the common code in a function called forward_base that can be called both for dynamic and hard voxelization?

2022-10-24 18:55 UTC, siddharthanpr commented on mmdet3d/models/detectors/centerpoint.py
> +            sub_model = SubModel_dynamicVoxel(self.cfg,
Can we combine both submodels with the suggestions above to reduce code copies please?

2022-10-25 00:39 UTC, meremeev commented on mmdet3d/apis/convert.py
> +    if model.with_dynamic_voxelization or model.cfg['model']['type'] == 'CenterPoint_dynamicVoxel':
ok, will remove

2022-10-25 00:41 UTC, meremeev commented on mmdet3d/models/detectors/centerpoint.py
> +        class SubModel_dynamicVoxel(torch.nn.Module):
Will not work. forward() functions of two submodels take different number if arguments

2022-10-25 00:48 UTC, meremeev commented on mmdet3d/models/detectors/centerpoint.py
> +                self.output_names = None
as i mention above, they have different numbet of args. I am not sure how onnx.export() would react on *args function.

2022-10-25 00:50 UTC, meremeev commented on mmdet3d/models/detectors/centerpoint.py
> +            sub_model = SubModel_dynamicVoxel(self.cfg,
see above. main issue is difference in number of input args.

2022-10-26 18:51 UTC, siddharthanpr commented on mmdet3d/models/detectors/centerpoint.py
> +                self.output_names = None
We can have two different forward functions
```if self.with_dynamic_voxelization:
    self.forward = self.forward_dynamic
else:
    self.forward = self.forward_hard
```

2022-10-26 18:51 UTC, siddharthanpr commented on mmdet3d/models/detectors/centerpoint.py
> +                self.output_names = None
we can have `forward_dynamic` take only 2 args while `forward_hard` can take 3

2022-10-26 18:57 UTC, siddharthanpr requested changes
lets split the forward function as suggested above

2022-10-27 01:17 UTC, meremeev commented on mmdet3d/models/detectors/centerpoint.py
> +                self.output_names = None
well, we can but it will not be simplier. I will play with vararg forward(). may be it will work.

2022-10-27 01:20 UTC, siddharthanpr commented on mmdet3d/models/detectors/centerpoint.py
> +            sub_model = SubModel_dynamicVoxel(self.cfg,
Yes if vararg works sure, otherwise we can do the above.. Because right now, if we want to add something to the constant buffer, things need to change in 2 places etc.

2022-10-27 01:48 UTC, siddharthanpr commented on mmdet3d/models/detectors/centerpoint.py
> +                self.output_names = None
Yes if vararg works sure, otherwise we can do the above.. Because right now, if we want to add something to the constant buffer, things need to change in 2 places etc.

2022-10-27 01:52 UTC, siddharthanpr commented on mmdet3d/models/detectors/centerpoint.py
> +                    voxel_features, feature_coors = args
nice! I like the readability

2022-10-27 03:33 UTC, siddharthanpr commented on mmdet3d/models/detectors/centerpoint.py
> +                if 'deterministic' in self.cfg.model['pts_voxel_layer']:
deterministic = True by default

2022-10-27 03:36 UTC, siddharthanpr commented on mmdet3d/models/detectors/centerpoint.py
>                      score_threshold=torch.tensor([self.cfg.model['pts_bbox_head']['bbox_coder']['score_threshold']]),
```suggestion
                    deterministic_voxelization=torch.tensor([deterministic' not in self.cfg.model['pts_voxel_layer'] or self.cfg.model['pts_voxel_layer']['deterministic']], dtype=torch.int)
                    score_threshold=torch.tensor([self.cfg.model['pts_bbox_head']['bbox_coder']['score_threshold']]),
```

2022-10-27 03:36 UTC, siddharthanpr commented on mmdet3d/models/detectors/centerpoint.py
> +                if 'deterministic' in self.cfg.model['pts_voxel_layer']:
use above suggestion

2022-10-27 03:37 UTC, siddharthanpr reviewed
One change for setting deterministic voxelization

2022-10-27 03:38 UTC, siddharthanpr commented on mmdet3d/models/detectors/centerpoint.py
>                      score_threshold=torch.tensor([self.cfg.model['pts_bbox_head']['bbox_coder']['score_threshold']]),
because not specifying deterministic means it is True by default. @ramchandra-karandikar can you confirm if this is true for dynamic voxelization also?

2022-10-28 19:27 UTC, siddharthanpr commented on mmdet3d/apis/convert.py
> +            model_name = model.cfg['model']['type'] + '_dynamicVoxel'
why do we change the type of the model here?

2022-10-28 19:27 UTC, siddharthanpr commented on mmdet3d/apis/convert.py
> +        model_name = model.cfg['model']['type'] + '_hardVoxel'
and here?

2022-10-28 19:28 UTC, siddharthanpr requested changes
the type of the model can just be CenterPoint I think. We can use the self.with_dynamic_voxelization to check what type of voxelization we use

2022-10-28 19:29 UTC, siddharthanpr commented
> One change for setting deterministic voxelization

I addressed this. Can you not change the model type manually in convert script?

2022-10-31 23:29 UTC, meremeev commented on mmdet3d/apis/convert.py
> +            model_name = model.cfg['model']['type'] + '_dynamicVoxel'
We did not change model typy. We name ONNX export by type of the model+ dynamic/hard voxel suffix to differenciate exportes. 
Since `CenterPoint_dynamicVoxel` class is still in repo and I do not want to have export name `CenterPoint_dynamicVoxel_dynamicVoxel`  we have second condition.

2022-10-31 23:30 UTC, meremeev commented on mmdet3d/apis/convert.py
> +        model_name = model.cfg['model']['type'] + '_hardVoxel'
see above

2022-10-31 23:41 UTC, meremeev commented
> > One change for setting deterministic voxelization
> 
> I addressed this. Can you not change the model type manually in convert script?

do you mean `onnx2trt_conversion.sh`? it does not change model type.It use ONNX export file name to name TRT engine file + CC and FP flags. Do you want to strip these flags?

2022-11-01 04:40 UTC, siddharthanpr approved these changes

2022-11-01 04:40 UTC, merged