introduce variable to support thresholding during inference
luminartech/mmdetection3d pull request #7
Opened 2022-08-25 01:31 UTC by ramchandra-karandikar

Creating draft PR. Need to test TensorRT generation with the new configuration file

2022-08-25 22:08 UTC, siddharthanpr commented on configs/centerpoint/centerpoint_03pillar_kitti_lum.py
> +cpp_inference_threshold_lum = 0.3
call this score_threshold_cpp_inference_lum

2022-08-25 22:08 UTC, siddharthanpr commented on configs/centerpoint/centerpoint_03pillar_kitti_lum.py
> +cpp_inference_threshold_lum = 0.3
```suggestion
score_threshold_cpp_inference_lum = 0.3
```

2022-08-25 22:08 UTC, siddharthanpr commented on mmdet3d/apis/trt_build.py
> +    cpp_inference_threshold_lum=centerpoint_config.cpp_inference_threshold_lum,
```suggestion
   score_threshold=centerpoint_config.score_threshold_cpp_inference_lum,
```

2022-08-25 22:11 UTC, siddharthanpr commented on configs/centerpoint/centerpoint_03pillar_kitti_lum.py
>      pts_voxel_layer=dict(
Disclaimer Not related to the PR: we have inconsistent values here ```
voxel_size=[0.2, 0.2, 16],
        max_voxels=(30000, 40000),
        point_cloud_range=[0, -55.2, -15, 128, 55.2, 15]),

2022-08-25 22:12 UTC, siddharthanpr commented on configs/centerpoint/centerpoint_03pillar_kitti_lum.py
>      pts_voxel_layer=dict(
can we llook into this in future PR?

2022-08-25 22:12 UTC, siddharthanpr requested changes
small changes

2022-08-25 22:15 UTC, ramchandra-karandikar commented on configs/centerpoint/centerpoint_03pillar_kitti_lum.py
>      pts_voxel_layer=dict(
Yes, I will create a separate PR for those. 
Need to clean-up unused variables

2022-08-28 09:55 UTC, siddharthanpr commented on configs/centerpoint/centerpoint_03pillar_kitti_lum.py
> -conversion = dict(
i think this is needed for engine conversion

2022-08-28 09:55 UTC, siddharthanpr commented on mmdet3d/apis/trt_build.py
> +   score_threshold=centerpoint_config.score_threshold_cpp_inference_lum,
can you format this.

2022-08-30 01:30 UTC, siddharthanpr commented
closing this since we figured out that -8, 8 is not needed

2022-08-30 01:30 UTC, closed without merging